version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam
    - gosec
    - goconst
    - gocyclo
  settings:
    goconst:
      ignore-tests: true

run:
  timeout: 5m
